---
### Confluent Cloud Connection
##
## The following is an example inventory file of the configuration required for setting up Confluent Platform with
## all components connecting to Kafka and Schema Registry in Confluent Cloud

all:
  vars:
    ansible_connection: ssh
    ansible_user: azureuser
    ansible_become: true
    ansible_ssh_private_key_file: <location for ssh key> 
    ccloud_kafka_enabled: true
    ccloud_kafka_bootstrap_servers: <kafka bootstrap> 
    ccloud_kafka_key: <API Key for CC>
    ccloud_kafka_secret: <API secret> 
    
    ccloud_schema_registry_enabled: true
    ccloud_schema_registry_url: <schema registry url> 
    ccloud_schema_registry_key: <schema registry api key>
    ccloud_schema_registry_secret: <schema registry api secret> 

    control_center_authentication_type: basic
    control_center_basic_users:
      admin:
        principal: c3admin
        password: CHANGE_ME 
        roles: Administrators
    
    kafka_connect_connectors:
     - name: nh-source-connector
       config:
        connector.class: "io.debezium.connector.postgresql.PostgresConnector"
        tasks.max: "1"
        database.hostname: "localhost"
        database.port: "5433"
        database.user: "testuser"
        database.password: "testuser123"
        database.dbname : "postgres"
        database.server.name: "dbname1"
        schema.whitelist: "public"
        table.include.list: "public.sellers,public.customers,public.products,public.orders"
        snapshot.mode: "always"
        topic.creation.enable: true
        value.converter: "org.apache.kafka.connect.json.JsonConverter"
        topic.creation.$alias.replication.factor: "3"
        topic.creation.groups: "nh"
        topic.creation.default.replication.factor: "3"
        topic.creation.default.partitions: "10"
        topic.creation.default.cleanup.policy: "compact"
        topic.creation.default.compression.type: "lz4"


kafka_connect:
  vars:
   kafka_connect_confluent_hub_plugins:
   - confluentinc/connect-transforms:1.4.3
   - debezium/debezium-connector-postgresql:1.9.3
  hosts:
   <hostname for kafka connect worker nodes> 

# (Optional) Install C3 for managing the connectors
control_center:
  hosts:
   <host name for c3>
